-- SQLBook: Code
-- Active: 1696994053996@@127.0.0.1@3306@phpmyadmin
DROP DATABASE IF EXISTS escuela;
CREATE DATABASE escuela CHARACTER SET utf8mb4;
USE escuela;

CREATE TABLE users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(30) NOT NULL,
  password VARCHAR(50) NOT NULL
);


CREATE TABLE materia (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(30) NOT NULL
);

CREATE TABLE profesor (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  apellido1 VARCHAR(100) NOT NULL,
  apellido2 VARCHAR(100)
);

CREATE TABLE curso (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL,
  turno VARCHAR(30) NOT NULL
  
);

CREATE TABLE alumno (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  apellido1 VARCHAR(100) NOT NULL,
  apellido2 VARCHAR(100),
  id_curso INT UNSIGNED NOT NULL,
  FOREIGN KEY (id_curso) REFERENCES curso(id)
  
);



CREATE TABLE cargo (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  id_materia INT UNSIGNED NOT NULL,
  id_profesor INT UNSIGNED NOT NULL,
  id_curso INT UNSIGNED NOT NULL,
  FOREIGN KEY (id_materia) REFERENCES materia(id),
  FOREIGN KEY (id_profesor) REFERENCES profesor(id),
  FOREIGN KEY (id_curso) REFERENCES curso(id)
);

